### ISSUE TITLE
Connecting to multiple unified remote servers

### ISSUE THREAD

**Issue by masterxdk** [DaviPtrs/hass-unified-remote#1]
Hi,

I was planning on using your integration to be able to turn off my kids computer using an automation and button on my HA.
But it seems like it only allows for one connection? Is that true?
If yes, any plans on making it compatible with more than one?

Thanks :)

**Comment by DaviPtrs** [comment]
Thanks for your idea, but I think it's a little overkill to use unified remote just for turn a computer off. Before this integration I used to turn off my computer by accessing using SSH (yes, you can install an ssh server on windows, works well just like on linux), and then sending the shutdown command. You can create a bash script to send the shutdown command for all your computers and add a shell command on your HA to call this script.

**Comment by masterxdk** [comment]
Hi, thanks for your reply. In theory it could be used to do more than just reboot. But right now thats my goal. I have two kids with each their pc. They are on a seperate vlan from my HA. Ive opened up the port for unified remore, but am reluctant to open up for SSH. I just thought it might be good being able to control more than one pc. Ill find another way :)
Thanks

**Comment by ghost** [comment]
For sure I'll implement this some time, but there's some critical changes that I have to handle first. Thanks for your suggestion!

**Comment by dex3r** [comment]
I would love to see this feature too. I would like to control two my own computers, using any remotes.
