### ISSUE TITLE
Enter MAC adress for Wake on Lan?

### ISSUE THREAD

**Issue by Kraechtshammer** [DaviPtrs/hass-unified-remote#10]
Hi, can you add the ability to also add the MAC adress to host config for enabling Wake on LAN functionality? Or is there some other reason that it doesn't work for me? I think especially that action would be great to have, so maybe there is a chance?

**Comment by DaviPtrs** [comment]
Hello, you should use the WOL native integration https://www.home-assistant.io/integrations/wake_on_lan/ because the Unified integration works connecting with the computer local control panel (localhost:9510/client), so it's not gonna work at all when the computer is powered off.
