### ISSUE TITLE
Component error: unified_remote - Integration 'unified_remote' not found.

### ISSUE THREAD

**Issue by frederico0102** [DaviPtrs/hass-unified-remote#13]
when i will restart ocurr this error, this error started after HA update
Component error: unified_remote - Integration 'unified_remote' not found.

**Comment by BrainFixer** [comment]
Same problem. This happened after HA updating to 2021.6.0. Now HA is 2021.6.3 but problem was not solved.

**Comment by frederico0102** [comment]
i fixed this removing the config and restarting, after this i insert the configs restart again, its works now
