### ISSUE TITLE
this integration no longer works with new versions of HA

### ISSUE THREAD

**Issue by elialbert** [DaviPtrs/hass-unified-remote#14]
my installed version didn't work at all and the integration no longer shows up in search.
I'd be happy to help if you can point me in the right direction?
thanks!

**Comment by DaviPtrs** [comment]
Reinstall the integration with the newest version of it

**Comment by elialbert** [comment]
it doesn't even show up in the home assistant integrations list anymore? I'd love to reinstall it but are you sure it's configured appropriately in the integrations "store"?

**Comment by elialbert** [comment]
ah or was it never in the store and I need to manually install. sorry, will try that!
