### ISSUE TITLE
error at loading and at service call

### ISSUE THREAD

**Issue by guegrer** [DaviPtrs/hass-unified-remote#3]
i have an error so component do not work when i try to call service :
full error log:
Oct 24 00:57:17 hass hass[20969]: 2020-10-24 00:57:17 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1774181392] name 'REMOTES' is not defined
Oct 24 00:57:17 hass hass[20969]: Traceback (most recent call last):
Oct 24 00:57:17 hass hass[20969]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/websocket_api/commands.py", line 138, in handle_call_service
Oct 24 00:57:17 hass hass[20969]:     await hass.services.async_call(
Oct 24 00:57:17 hass hass[20969]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/core.py", line 1335, in async_call
Oct 24 00:57:17 hass hass[20969]:     task.result()
Oct 24 00:57:17 hass hass[20969]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/core.py", line 1374, in _execute_service
Oct 24 00:57:17 hass hass[20969]:     await self._hass.async_add_executor_job(handler.func, service_call)
Oct 24 00:57:17 hass hass[20969]:   File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Oct 24 00:57:17 hass hass[20969]:     result = self.fn(*self.args, **self.kwargs)
Oct 24 00:57:17 hass hass[20969]:   File "/home/homeassistant/.homeassistant/custom_components/unified_remote/__init__.py", line 146, in handle_call
Oct 24 00:57:17 hass hass[20969]:     remote = REMOTES.get_remote(remote_name)
Oct 24 00:57:17 hass hass[20969]: NameError: name 'REMOTES' is not defined

at loading seems it dont find remotes.yml whereas it is present..
Oct 24 00:52:03 hass hass[20969]: 2020-10-24 00:52:03 ERROR (MainThread) [custom_components.unified_remote] Remotes file not found. Path:/config/custom_components/unified_remote/cli/remotes.yml

thanks for help me i would love to be able to manage unified from homeassistant

**Comment by DaviPtrs** [comment]
Where do you use home assistant? Docker?

**Comment by DaviPtrs** [comment]
How do you use home assistant? Docker?

**Comment by guegrer** [comment]
sorry for the response time i use the python environement version of HA 
every new upate guess

need to modify the __init__.py:

REMOTE_FILE_PATH = "/home/homeassistant/.homeassistant/custom_components/unified_remote/cli/remotes.yml"

thanks for the integration
