### ISSUE TITLE
Help with Unified.Command

### ISSUE THREAD

**Issue by frederico0102** [DaviPtrs/hass-unified-remote#8]
Hello, I have a doubt, in the Unified Remote android application I can send cmd commands, I would like to know if it is possible to do the same, because unfortunately there is no such command in the web client

As i did

target: Casa
action: execute
remote_id: Unified.Command
Values:
  - Value: "nircmd setdefaultsounddevice tv"

![Screenshot_1](https://user-images.githubusercontent.com/20929655/99668999-367de200-2a4d-11eb-98eb-b705bfec30d0.png)

As it is in the tasker

![photo_2020-11-19_09-52-42](https://user-images.githubusercontent.com/20929655/99669000-37167880-2a4d-11eb-8e4a-b2d5bc0222e9.jpg)

in the app
![intheapp](https://user-images.githubusercontent.com/20929655/99669213-8197f500-2a4d-11eb-99a3-b87e81d18bff.jpg)

**Comment by frederico0102** [comment]
![photo_2020-11-19_11-44-50](https://user-images.githubusercontent.com/20929655/99681259-b2335b00-2a5c-11eb-983d-4a20d4c7b873.jpg)
Also in the application you have the answer to this cmd command, I would like to know if it is possible to recover it, follow an example.
(I'll use it for other functions like knowing if windows is blocked and things like that)

**Comment by DaviPtrs** [comment]
Can you send me the full payload used on cmd sending? "Extras" values are already available, but if there's another field to handle I will add it for sure, is just because I don't use Unified Remote to send cmds (I think it's not secure)

**Comment by frederico0102** [comment]
Sorry you hear an error of mine when sending the command, I made the correction by adding Extras: before the Values
now the sending of the command worked and executed on windows correctly, what I would like to recover would be the return of the Command sent

**Comment by frederico0102** [comment]
Sorry you hear an error of mine when sending the command, I made the correction by adding Extras: before the Values
now the sending of the command worked and executed on windows correctly

```
target: Casa
action: execute
remote_id: Unified.Command
extras:
  Values:
    - Value: nircmd setdefaultsounddevice tv
```

works well

**Comment by frederico0102** [comment]
but in the unified remote application I can receive the response from the command such as a ping it returns the result, I would like to receive this resulting in the HA, thanks and sorry for my bad english

**Comment by DaviPtrs** [comment]
No problem. I don't think there's a way to retrieve that information and show them on Home Assistant unless you use the Ping Integration instead of sending ping commands via Unified Remote, since it's a service and it can only execute things. I probably will have to create a sensor to show any information that you receive from Unified Remote, but it will be a major update since I don't know how to do this yet, but anyway, you can create a new issue requesting this feature, and someone (probably me) will work on it soon. =)

**Comment by frederico0102** [comment]
right, i will create a new issue requesting, thanks
